# 新版本 Flutter 已经不需要旧的 .symlinks 加载脚本了！
platform :ios, '14.0' # 对齐原项目的 14.0，解决部署目标过低问题

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

# 修复：强制所有 Pod 使用 14.0 部署目标，解决警告
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
    end
  end
end
